site_name: Quad9 Documentation
site_url: https://quad9dns.github.io/documentation
  #repo_url: https://github.com/Quad9DNS/documentation

plugins:
  - social:
      cards_layout_options:
        background_color: "#2E303E"
  - search
  - i18n:
      reconfigure_material: true
      fallback_to_default: false
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: es
          name: Español
          build: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
     alternate_style: true

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: images/favicon.svg
  logo: assets/logo_light.svg
  font: false
  features:
    - navigation.index
    - navigation.sections
      #    - navigation.instant
    - toc.integrate
    - content.code.copy
    - header.autohide
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to Light Mode
      primary: pink
      accent: pink
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to Dark Mode
      primary: pink
      accent: pink

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: Français
      link: /fr/
      lang: fr
    - name: Español
      link: /es/
      lang: es
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/quad9dns
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/quad9-dns/
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/Quad9/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/quad9dns/
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@quad9dns

copyright: |
  &copy; 2023-2024 <a href="https://quad9.net"  target="_blank" rel="noopener">Quad9.net</a>
  All content licensed under Creative Commons Attribution-ShareAlike 4.0 License unless otherwise specified
